---
name: "InjectManager"
inject_directory: "injects/"
inject_count: 15
inject_path_count: 3
cache_directory: "cache/"
results_directory: "results/"
max_teams: 12
template_directory: "src/templates/"
log_level: 4
log_file: "InjectManager.log"
db: "db.json"
sheets_api_key: ".secrets/google.json"
gmail_creds: ".secrets/gmail.json"
ists_creds: ".secrets/ists.json"
